starter/modules/users/models.py
from typing import List

from alchemical import Model
from sqlalchemy import Integer, ForeignKey, String
from sqlalchemy.orm import Mapped, mapped_column, relationship
from werkzeug.security import generate_password_hash, check_password_hash

from starter.core.persistence.mixins import AuthoringMixin


class Role(Model):
    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    key: Mapped[str] = mapped_column(String(180), nullable=False, unique=True)
    name: Mapped[str] = mapped_column(String(180), nullable=False, unique=True)

    users: Mapped[List['User']] = relationship(
        back_populates='role',
        order_by='asc(User.username)'
    )

    def __repr__(self):
        return f'<Role {self.key}>'


class User(Model, AuthoringMixin):
    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    username: Mapped[str] = mapped_column(String(180), nullable=False, unique=True)
    digest: Mapped[str] = mapped_column('password', String(180), nullable=True)
    role_id: Mapped[int] = mapped_column(ForeignKey('role.id'), nullable=False, index=True)
    first_name: Mapped[str] = mapped_column(String(180), nullable=True)
    last_name: Mapped[str] = mapped_column(String(180), nullable=True)

    role: Mapped['Role'] = relationship(
        back_populates='users',
        foreign_keys='User.role_id'
    )

    @property
    def password(self):
        return None

    @password.setter
    def password(self, value):
        if value:
            self.digest = generate_password_hash(value)

    @property
    def name(self):
        if self.first_name and self.last_name:
            return f'{self.last_name} {self.first_name}'
        elif self.first_name:
            return self.first_name
        elif self.last_name:
            return self.last_name

        return None

    def check_password(self, password):
        return self.digest and check_password_hash(self.digest, password)

    def __repr__(self):
        return f'<User {self.username}>'

starter/modules/users/forms.py
from flask_wtf import FlaskForm
from wtforms.fields.simple import SubmitField, PasswordField, StringField
from wtforms.validators import InputRequired, Length, Optional
from wtforms_sqlalchemy.fields import QuerySelectField

from starter.modules.users.repositories import RoleRepository


class UserFormMixin:
    username = StringField('Felhasználónév', validators=[
        InputRequired('Hiányzik az érték!'),
        Length(max=180, message='Túl hosszú érték!')
    ])
    role = QuerySelectField('Szerepkör', query_factory=RoleRepository.find_all, get_label='name')
    first_name = StringField('Keresztnév', validators=[
        Optional(),
        Length(max=180, message='Túl hosszú érték!')
    ], filters=[lambda x: x or None])
    last_name = StringField('Vezetéknév', validators=[
        Optional(),
        Length(max=180, message='Túl hosszú érték!')
    ], filters=[lambda x: x or None])
    submit = SubmitField('Mentés')


class CreateUserForm(FlaskForm, UserFormMixin):
    password = PasswordField('Jelszó', validators=(
        InputRequired(message='Hiányzik az érték!'),
    ))


class EditUserForm(FlaskForm, UserFormMixin):
    password = PasswordField('Password', validators=(
        Optional(),
    ))

starter/modules/users/__init__.py
from flask import Blueprint

bp = Blueprint('users', __name__)

from starter.modules.users import routes

starter/modules/users/routes.py
from flask import flash, redirect, url_for, request, render_template, abort
from sqlalchemy.exc import SQLAlchemyError

from starter.core.persistence.decorators import param
from starter.core.security.decorators import is_granted
from starter.modules.users import bp
from starter.modules.users.forms import CreateUserForm, EditUserForm
from starter.modules.users.models import User
from starter.modules.users.repositories import UserRepository


@bp.route('/')
@is_granted('ROLE_ADMIN')
def list_all():
    if 'search' in request.args:
        users = UserRepository.find_all_by_username_like(request.args['search'])
    else:
        users = UserRepository.find_all()

    return render_template('users/list.html', users=users)


@bp.route('/letrehozas', methods=('GET', 'POST'))
@is_granted('ROLE_ADMIN')
def create():
    user = User()
    form = CreateUserForm(obj=user)

    if form.validate_on_submit():
        form.populate_obj(user)

        try:
            UserRepository.save(user)
            flash('Felhasználó létrehozva.')

            return redirect(url_for('users.list_all'))
        except SQLAlchemyError as err:
            if 'duplicate' in str(err).lower():
                flash('A megadott felhasználónévvel már létezik felhasználó!')
            else:
                flash('Hiba történt az új felhasználó létrehozása során!')

    return render_template('users/create.html', form=form)


@bp.route('/szerkesztes/<username>', methods=('GET', 'POST'))
@is_granted('ROLE_ADMIN')
@param('user', UserRepository.find_by_username, 'username')
def edit(user):
    form = EditUserForm(obj=user)

    if form.validate_on_submit():
        form.populate_obj(user)

        try:
            UserRepository.save(user)
            flash('Felhasználó mentve.')

            return redirect(url_for('users.edit', username=user.username))
        except SQLAlchemyError as err:
            if 'duplicate' in str(err).lower():
                flash('A megadott felhasználónévvel már létezik felhasználó!')
            else:
                flash('Hiba történt a felhasználó mentése során!')

    return render_template('users/edit.html', form=form)


@bp.route('/torles/<username>', methods=('POST',))
@is_granted('ROLE_ADMIN')
@param('user', UserRepository.find_by_username, 'username')
def delete(user):
    try:
        UserRepository.delete(user)
        flash('Felhasználó törölve.')
    except SQLAlchemyError:
        flash('Hiba történt a felhasználó törlése közben!')

    return redirect(url_for('users.list_all'))

starter/templates/users/_form.html
<form method="post">
    {{ form.csrf_token }}

    <div class="mb-3">
        {{ form.username.label(class="form-label") }}
        {{ form.username(class="form-control") }}
        {% if form.username.errors %}
            <ul>
                {% for error in form.username.errors %}
                    <li class="text-danger">{{ error }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    </div>

    <div class="mb-3">
        {{ form.password.label(class="form-label") }}
        {{ form.password(class="form-control") }}
        {% if form.password.errors %}
            <ul>
                {% for error in form.password.errors %}
                    <li class="text-danger">{{ error }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    </div>

    <div class="mb-3">
        {{ form.role.label(class="form-label") }}
        {{ form.role(class="form-control") }}
        {% if form.role.errors %}
            <ul>
                {% for error in form.role.errors %}
                    <li class="text-danger">{{ error }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    </div>

    <div class="mb-3">
        {{ form.last_name.label(class="form-label") }}
        {{ form.last_name(class="form-control") }}
        {% if form.last_name.errors %}
            <ul>
                {% for error in form.last_name.errors %}
                    <li class="text-danger">{{ error }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    </div>

    <div class="mb-3">
        {{ form.first_name.label(class="form-label") }}
        {{ form.first_name(class="form-control") }}
        {% if form.first_name.errors %}
            <ul>
                {% for error in form.first_name.errors %}
                    <li class="text-danger">{{ error }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    </div>

    <div class="row g-3 align-items-center">
        <div class="col-auto">
            {{ form.submit(class="btn btn-primary", onclick="return confirm('" ~ confirm_message ~ "')") }}
        </div>
        <div class="col-auto">
            <a href="{{ url_for('users.list_all') }}" class="btn btn-secondary">Mégse</a>
        </div>
    </div>
</form>

starter/templates/users/create.html
{% extends 'base.html' %}

{% set title = 'Felhasználó létrehozása' %}
{% set confirm_message = 'Felhasználó létrehozása?' %}

{% block content %}
    <div class="mt-5">
        {% include 'users/_form.html' %}
    </div>
{% endblock %}

starter/templates/users/edit.html
{% extends 'base.html' %}

{% set title = 'Felhasználó szerkesztése' %}
{% set confirm_message = 'Felhasználó mentése?' %}

{% block content %}
    <div class="mt-5">
        {% include 'users/_form.html' %}
    </div>
{% endblock %}

starter/templates/users/list.html
{% extends 'base.html' %}

{% set title = 'Felhasználók' %}
{% set search = True %}

{% block content %}
    <table class="table mt-5">
        <thead>
        <tr>
            <th>Felhasználónév</th>
            <th>Szerepkör</th>
            <th>Név</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        {% for user in users %}
            <tr>
                <td>{{ user.username }}</td>
                <td>{{ user.role.name }}</td>
                <td>{% if user.name %}{{ user.name }}{% endif %}</td>
                <td>
                    <div class="d-flex">
                        <a href="{{ url_for('users.edit', username=user.username) }}" class="btn btn-primary mx-1">
                            Szerkesztés
                        </a>
                        <form method="post" action="{{ url_for('users.delete', username=user.username) }}" class="mx-1">
                            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>

                            <button type="submit" class="btn btn-danger"
                                    onclick="return confirm('Felhasználó törlése?')">
                                Törlés
                            </button>
                        </form>
                    </div>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <div class="mt-3">
        <a href="#top">Oldal teteje</a>
    </div>
{% endblock %}